// This file will be auto-generated by SubQuery codegen from protobuf definitions
// Run: yarn codegen

// Placeholder for Cosmos message types
export interface MsgSwapExactAmountInMessage {
  block: {
    header: { height: number };
    block: { header: { height: number } };
  };
  tx: {
    hash: string;
  };
  idx: number;
  msg: {
    decodedMsg: {
      sender: string;
      tokenIn?: {
        denom: string;
        amount: string;
      };
      tokenOutMinAmount: string;
      routes: Array<{
        poolId: number;
        tokenOutDenom: string;
      }>;
    };
  };
}