// This file will be auto-generated by SubQuery codegen
// Run: yarn codegen

// Placeholder type definitions for TypeScript compilation
export interface Pool {
  id: string;
}

export interface Swap {
  id: string;
  sender: string;
  txHash: string;
  blockHeight: bigint;
  tokenInDenom?: string;
  tokenInAmount?: bigint;
  tokenOutMin: bigint;
}

export interface SwapRoute {
  id: string;
  poolId: string;
  swapId: string;
  tokenInDenom?: string;
  tokenOutDenom: string;
}

// These will be generated by codegen from GraphQL schema
export const Pool: any = {};
export const Swap: any = {};
export const SwapRoute: any = {};