[package]
name = "privachain-arti-node"
version = "0.1.0"
edition = "2021"

[dependencies]
arti-client = { version = "0.24", features = ["native-tls", "tokio"] }
tor-rtcompat = { version = "0.24", features = ["tokio", "rustls"] }
toml = "0.8.2"
dirs = "5.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
anyhow = "1.0"

[lib]
name = "privachain_arti_node"
path = "src/lib.rs"
